# Crear o actualizar un formulario
POST {{API_URL}}email-notifications
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Title notification",
  "ManagerID": 1,
  "TypeID":1
}

###
# Obtener todos los formularios
GET {{API_URL}}email-notifications
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# Obtener formularios con paginación
GET {{API_URL}}email-notifications/1?rows=50
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# Eliminar un formulario
POST {{API_URL}}email-notifications/delete
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": 1
}
