# Obtener todos los niveles
GET {{API_URL}}level
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Obtener niveles con paginación
GET {{API_URL}}level/1?rows=50
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Añadir un nuevo nivel
POST {{API_URL}}level
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "level": "Nuevo Nivel",
  "description": "Descripción del nuevo nivel"
}

###

# Eliminar un nivel
POST {{API_URL}}level/delete
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": 1
}
